IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2015-09-30 20:05:53 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://avatars.githubusercontent.com/u/133209?v=3", githubOwnerLogin = "lamby", githubOwnerUrl = "https://api.github.com/users/lamby", githubOwnerId = 133209, githubOwnerGravatarId = Just ""}, issueCommentUrl = "https://api.github.com/repos/lamby/django-slack/issues/comments/144524906", issueCommentCreatedAt = GithubDate {fromGithubDate = 2015-09-30 20:05:53 UTC}, issueCommentBody = "> popping a key with a None value does not produce a Python KeyError.\r\n\r\nCan you elaborate? ``{'a': None}.pop('a')`` does not raise a ``KeyError``. I think something else is up.", issueCommentId = 144524906}